# -*- coding: utf-8 -*-
"""2_Sequência_de_Fibonacci.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Rffc7GeXsgdk6RvSew0iQ9Kyq0nlh76t
"""

def fibonacci(limite):
    fib = [0, 1] # Inicia Fibonacci com os valores de 0 e 1
    while fib[-1] < limite: # Calcula os próximos valores da sequência até atingir o limite que sera o numero informado mais na frente no código
        fib.append(fib[-1] + fib[-2])
    return fib

def verifica_fibonacci(numero):     # Função que Calcula a sequência de Fibonacci até o número desejado
    seq_fib = fibonacci(numero)
    if numero in seq_fib: # Testando se o número informado pertence a sequência
        return f"{numero} pertence à sequência de Fibonacci."
    else:
        return f"{numero} não pertence à sequência de Fibonacci."

# Como usar:
print(verifica_fibonacci(19)) # Dentro da função passar o argumento do número a ser verificado

