# -*- coding: utf-8 -*-
"""Inverter_String.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pH7Q8yA5Q0ZF5TLmLDK_DVMRkny_9BsG
"""

string = "Hello Target!"  # String a ser invertida
reverse_string = ""  # String invertida, inicialmente vazia

# Percorre a string da direita para a esquerda, adicionando cada caractere à nova string invertida
for i in range(len(string)-1, -1, -1):
    reverse_string += string[i]

# Imprime a string invertida
print(reverse_string)

